server:
  port: 8080

shiro:
  ws:
    client:
      enable: true
      url: "ws://127.0.0.1:3001"
  task-pool:
    # 核心线程数（默认线程数）
    core-pool-size: 20
    # 缓冲队列大小
    queue-capacity: 200
    # 允许线程空闲时间（单位：默认为秒）
    keep-alive-time: 10
    # 最大线程数
    max-pool-size: 32
    # 线程池名前缀
    thread-name-prefix: "OneBotEvent-"
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://192.168.1.104/QQMessage
    redis:
      host: 192.168.1.104
lomu-bot:
  mail:
    host: smtp.qq.com
    port: 465
    from: 3141298408@qq.com
    user: 3141298408
    pass: ====
    starttls: true
    ssl: true