server:
  port: 8080

shiro:
  ws:
    client:
      enable: true
      url: "ws://127.0.0.1:3001"
spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://192.168.1.104/QQMessage
    redis:
      host: 192.168.1.104